#!/bin/bash

echo "copying gnome2 to ~/.gnome2/"
cp -R gnome2/* ~/.gnome2/

echo "copying local to ~/.local/"
cp -R local/* ~/.local/

echo "copying nanorc to ~/.nanorc"
cp nanorc ~/.nanorc

echo "copying bash_aliases to ~/.bash_aliases"
cp bash_aliases ~/.bash_aliases

echo "copying bashrc to ~/.bashrc"
cp bashrc ~/.bashrc

# install curl if not exist
if [ -z `which curl` ]; then
    echo "installing curl"
    sudo aptitude install curl
fi

# GIT AWESOMENESS
# install git-core
if [ -z `which git` ]; then
    echo "installing git-core"
    sudo aptitude install git-core git-completion
fi
# install defunkt's hub
if [ -z `which hub` ]; then
    echo "installing hub"
    curl http://chriswanstrath.com/hub/standalone -sLo ~/hub && chmod 755 ~/hub
    sudo mv ~/hub /usr/bin/hub && sudo chown root /usr/bin/hub
fi

source ~/.bashrc

echo "please close all terminals to finish the installation"
exit

